server.port: 9124

spring.datasource:
  url: "jdbc:h2:mem:ktl"
  driverClassName: org.h2.Driver
  username: sa
  password: ""
  data: "classpath*:data.sql"
spring.jpa:
  database-platform: org.hibernate.dialect.H2Dialect
spring.h2.console.enabled: true
spring:
  jpa:
    show-sql: true

